# -*- coding: utf-8 -*-
"""Video_Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13MXZgYiY0Txf9gyZkoOzw-MVDIFI0HUf
"""

#packages
import random
import time

"""#Object Creation

"""

#Object Creation
#Character
class Character:
  def __init__(self,name,player_class):
    self.name = name
    self.player_class = player_class
    self.level = 1
    self.xp = 0
    self.max_hp = 50
    self.hp = self.max_hp
    self.min_damage = 1
    self.max_damage = 10
    self.inventory = []
    self.equipment = {
      "Weapon": None,
      "Helmet": None,
      "Chest": None,
      "Boots": None
      }
    self.gold = 0
  def attack(self):
    return random.randint(self.min_damage, self.max_damage)

  def equip(self, item):
    old_item = self.equipment[item.slot]
    if old_item:
      self.max_hp -= old_item.hp_bonus
      self.min_damage -= old_item.min_dmg_bonus
      self.max_damage -= old_item.max_dmg_bonus
    self.equipment[item.slot] = item
    self.max_hp += item.hp_bonus
    self.min_damage += item.min_dmg_bonus
    self.max_damage += item.max_dmg_bonus
    print(f"{self.name} equipped {item.name}!")

#Monster
class Mob:
  def __init__(self, name, hp, min_damage, max_damage, xp_reward, mob_type):
    self.name = name
    self.mob_type = mob_type
    self.hp = hp
    self.min_damage = min_damage
    self.max_damage = max_damage
    self.xp_reward = xp_reward
  def attack(self):
    return random.randint(self.min_damage, self.max_damage)

#Equipment
class Item:
  def __init__(self, name, slot, hp_bonus=0, min_dmg_bonus=0, max_dmg_bonus=0):
    self.name = name
    self.slot = slot
    self.hp_bonus = hp_bonus
    self.min_dmg_bonus = min_dmg_bonus
    self.max_dmg_bonus = max_dmg_bonus

"""#Functions"""

def Start_Game():
  global player

  print("Welcome! Let's get started.")
  player_name = input("What is your character's name?\n")
  player_class = input("What is your character's class?\n")
  player = Character(player_name, player_class)
  print(f"{player.name} is a brand new {player.player_class} looking to enter the world of adventuring. Good luck!")
  Dungeon_creation(1)

def Level_Up(player):
  xp_needed = player.level*5 - 2
  if player.xp >= xp_needed:
    player.level += 1
    player.min_damage += 2
    player.max_damage += 3
    player.max_hp += 10
    player.hp = player.max_hp
    print(f"{player.name} leveled up! They are now level {player.level} and have been fully healed!\n")
    player.xp -= xp_needed
  else:
    print(f"{player.name} needs {xp_needed - player.xp} more XP to reach level {player.level + 1} \n")
  time.sleep(1)

def Combat(player, mob):
  while player.hp > 0 and mob.hp >0:
    choice = input("Choose an action:\n1.Attack\n2.Heal\n3.Run\n4.Inspect\n")
    if choice == '1':
      player_damage = player.attack()
      mob.hp -= player_damage
      print(f"{player.name} hits {mob.name} for {player_damage} damage!")
      print(f"{mob.name} HP: {max(0, mob.hp)}\n")
      time.sleep(.4)

      if mob.hp <= 0:
        break
      mob_damage = mob.attack()
      player.hp -= mob_damage
      print(f"{mob.name} hits {player.name} for {mob_damage} damage")
      print(f"{player.name} HP: {max(0,player.hp)}\n")
      time.sleep(.4)

    elif choice =='2':
      player.hp = min(player.max_hp, player.hp+10)
      print(f"{player.name} heals for 10 HP!")
      print(f"{player.name} HP: {player.hp}\n")

      mob_damage = mob.attack()
      player.hp -= mob_damage
      print(f"{mob.name} hits {player.name} for {mob_damage} damage")
      print(f"{player.name} HP: {max(0,player.hp)}\n")
      time.sleep(.4)

    elif choice == "3":
      print("You ran away and escaped the dungeon.")
      return "Ran_away"

    elif choice == "4":
      print(f"Monster: {mob.name}\nMonster HP: {mob.hp}\nMonster Type: {mob.mob_type}")

    else:
      print("Please input a valid option.")

  if player.hp > 0:
    print(f"{player.name} defeated the {mob.name}!")
    player.xp += mob.xp_reward
    print(f"{player.name} gained {mob.xp_reward} XP!")
    print(f"{player.name} now has a total of {player.xp} XP.")
    Level_Up(player)
    return "Victory"
  else:
    print(f"{player.name} was defeated!")
    return "Defeat"

def Spawn_Mob():
  monsters = [
    ("Goblin", 10, 1, 5, 1,"Humanoid"),
    ("Wolf", 15, 2, 6, 1, "Beast"),
    ("Bandit", 20, 3, 5, 2, "Humanoid"),
    ("Rat", 10, 2, 5, 1, "Beast")
  ]
  monster = random.choice(monsters)
  return Mob(*monster)

def Spawn_Boss():
  bosses = [
    ("Bandit Leader", 45, 3, 9, 4,"Humanoid"),
    ("Alpha Wolf", 35, 4, 10, 4, "Beast"),
    ("Goblin Leader", 35, 2, 8, 4, "Humanoid")
  ]
  boss = random.choice(bosses)
  return Mob(*boss)

def Loot_Drop():
  loot_table = [
      Item("Sharp Stick", "Weapon", min_dmg_bonus=1),
      Item("Rusty Sword", "Weapon", min_dmg_bonus=2, max_dmg_bonus=3),
      Item("Paper Hat", "Helmet", hp_bonus=1),
      Item("Thin Shirt", "Chest", hp_bonus=2),
      Item("Mocassins", "Boots", hp_bonus=1)
  ]


  if random.random() < 0.25:
    return random.choice(loot_table)
  return None

def Handle_Loot(player,mob):
  loot = Loot_Drop()
  if loot:
    print(f"The {mob.name} dropped a {loot.name}!")
    choice = input("Equip it? Y or N\n").lower()
    if choice == "y":
      player.equip(loot)
    else:
      player.inventory.append(loot)
      print(f"{loot.name} was added to your inventory.")

def Continue():
  while True:
    choice = input("Where would you like to go next?\n1. Shop\n2. Inn\n3. Dungeon\n4. Retire\n")
    if choice == '1':
      pass

    elif choice == '2':
      #player.gold -= 10
      player.hp = player.max_hp
      print("You spent 10 gold to rest at the inn. You wake up feeling refreshed.")
      print(f"{player.name} is restored to {player.max_hp} health.")

    elif choice == '3':
      while True:
        try:
          difficulty = int(input("How difficult of a dungeon do you want to explore? (1-10)"))
          if 1 <= difficulty <= 10:
            Dungeon_creation(difficulty)
            break
          print("Please choose a difficulty between 1 and 10.")
        except ValueError:
          print("Please enter a number between 1 and 10.")

    elif choice == '4':
      print(f"{player.name} decided to end their career as a {player.player_class}. They retired at level {player.level} and lived a peaceful life.")
      print("Game Over")
      break
    else:
      print("Please input a valid option.")

def Dungeon_creation(difficulty):
  print(f"{player.name}, a {player.player_class}, enters the dungeon.")
  floors = difficulty + 1
  floor_count = 1
  while floor_count < floors:
    mob = Spawn_Mob()
    print(f"A {mob.name} appeared!")
    time.sleep(1)
    result = Combat(player,mob)
    time.sleep(.5)
    if result == "Defeat" or result == "Ran_away":
      print("Game over.")
      break
    else:
      Handle_Loot(player,mob)
      mob = Spawn_Mob()
      print(f"A {mob.name} appeared!")
      time.sleep(1)
      result = Combat(player,mob)
      if result == "Defeat" or result == "Ran_away":
        print("Game over.")
        break
      Handle_Loot(player,mob)
      while True:
        option = input("Continue deeper into the dungeon? Y or N\n").lower()
        if option == "y":
          break
        elif option == "n":
          print("You decide to leave the dungeon.")
          return
        print("Please input Y or N.")
      floor_count += 1
      time.sleep(.5)
      print(f"You descend to the next floor: Floor {floor_count}\n")
      time.sleep(.5)

  if floor_count >= floors and player.hp > 0:
    boss = Spawn_Boss()
    print(f"You found the boss! It's a {boss.name}! Prepare to fight.")
    time.sleep(1)
    result = Combat(player,boss)
    time.sleep(.5)
    if player.hp > 0:
      Handle_Loot(player, boss)
      Handle_Loot(player, boss)
      print(f"You cleared the dungeon on difficulty {difficulty}. You are currently level {player.level}. Keep going?")
      Continue()
    else:
      print("Game over!")

"""#Game Testing"""

Start_Game()